### ISSUE TITLE
New post fails after changing permalink

### ISSUE THREAD

**Issue by ryomo56** [roots/bedrock#453]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

New post fails after changing permalink

## Steps to reproduce

1 docker-compose.yml

```
version: "2"
services:
  apache-bedrock5:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./bedrock:/var/www/html/bedrock:rw
      - ./etc:/etc/apache2
    environment:
      VIRTUAL_HOST: example.com
      WORDPRESS_DB_PASSWORD: root
      CERT_NAME: default
    depends_on:
      - bedrockmysql
    restart: always
    tty: true
    logging:
      options:
        max-size: 5m
        max-file: "10"

  bedrockmysql:
    image: mysql:5.7
    volumes:
            - ./mysql_init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

networks:
  default:
    external:
      name: shared
```

2 Dockerfile

```
FROM php:7.3.7-apache

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer && \
    apt update && \
    docker-php-ext-install pdo_mysql mysqli mbstring && \
    apt install zip unzip && \
    apt install -y procps && \
    composer create-project roots/bedrock && \
    chown www-data:www-data -R /var/www/html/bedrock

EXPOSE 80

```
  
3 .env

```
#DB_NAME=bedrockmysql
#DB_USER=root
#DB_PASSWORD=root

# Optionally, you can use a data source name (DSN)
# When using a DSN, you can remove the DB_NAME, DB_USER, DB_PASSWORD, and DB_HOST variables
# DATABASE_URL=mysql://database_user:database_password@database_host:database_port/database_name
DATABASE_URL=mysql://root:root@172.20.0.3:3306/bedrockmysql

# Optional variables
#DB_HOST=bedrockmysql:3306
#DB_PREFIX=wp_

#WP_ENV=newsun
#I modified
WP_HOME=https://example.com
WP_SITEURL=${WP_HOME}/wp

# Generate your keys here: https://roots.io/salts.html
AUTH_KEY='****************************************************************'
SECURE_AUTH_KEY='****************************************************************'
LOGGED_IN_KEY='****************************************************************'
NONCE_KEY='****************************************************************'
AUTH_SALT='****************************************************************'
SECURE_AUTH_SALT='****************************************************************'
LOGGED_IN_SALT='****************************************************************'
NONCE_SALT='****************************************************************'  

```

4 docker-compose up -d --build
 
5 Container launch

  6 Install WordPress 
Access to wp/wp-admin/post.php  

7 Post published
Access to wp/wp-admin/post.php
<img width="1332" alt="スクリーンショット 2019-07-27 14 49 05" src="https://user-images.githubusercontent.com/22230993/61991086-5504e080-b086-11e9-8c99-27cf14fdcb9b.png">
 
8 Changing permalink to Post name 
Access to wp/wp-admin/options-permalink.php  
<img width="1600" alt="スクリーンショット 2019-07-27 14 10 42" src="https://user-images.githubusercontent.com/22230993/61991103-6cdc6480-b086-11e9-9dae-24905a1756ed.png">

9 Post published again

10 Publishing failed
<img width="1135" alt="スクリーンショット 2019-07-27 14 04 43" src="https://user-images.githubusercontent.com/22230993/61991106-749c0900-b086-11e9-8f87-dd070054df8c.png">

**Expected behavior:** I want to use 'post name' for posting new note  

**Actual behavior:** Publishing failed

**Reproduces how often:** [100%]

## Versions

1.12.7

## What I want to ask you

I have not identified the cause. if you need more information, feel free to ask me.
